<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/13
 * Time: 14:49
 * Auther sl
 */

namespace app\admin\logicModel;
use think\Model;
use app\admin\logicModel\MyException;
use app\admin\model\Article  ;
class ArticleLogic extends Model
{
    private $Article = '';
  function initialize()
  {
      parent::initialize(); // TODO: Change the autogenerated stub
      $this->Article = new Article();

  }

    public function saveArticle($data)
    {
        try {

            if (empty($data)){
                throw  new MyException('数据格式不对');
            }
            if (empty($data['article_id'])){
                $this->Article->data($data);
                $re = $this->Article->save();
                $msg = '添加';
            }else{
                $re =  $this->Article->update($data);
                $msg = '更新';
            }

            if (empty($re)){
                throw  new MyException($msg.'失败');
            }
            return format_data($re,'成功',true);
        } catch (MyException $e) {
               return format_data([],$e->getMessage(),true);
        }catch (\Exception $e) {
              return format_data([],$e->getMessage(),false);
        }
    }
    
    public function getOne($id){
        try {
            if (empty($id)){
                throw  new MyException('数据格式不对');
            }
            $re = $this->Article->where('article_id', $id)
                ->find();
            if (empty($re)){
                throw  new MyException('插入失败');
            }
            return format_data($re,'成功',true);
        } catch (MyException $e) {
            return format_data([],$e->getMessage(),true);
        }catch (\Exception $e) {
            return format_data([],$e->getMessage(),false);
        }
    }
}