<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/14
 * Time: 10:44
 * Auther sl
 */

namespace app\admin\logicModel;


use think\Model;
use app\admin\model\ArticleDetail;
use app\admin\logicModel\MyException;
class ArticleDetailLogic extends Model
{
    private $Model = '';
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Model = new ArticleDetail();
    }

    public function getOne($id)
    {
        try {
            if (empty($id)){
                throw new MyException('article_id 不能为空');
            }
            $re =  $this->Model->where('art_id', $id)->find();;
            if (empty($re)){
                throw new MyException('失败');
            }
            return format_data($re,'成功',true);
        }  catch (\MyException $e) {
            return format_data([],$e->getMessage(),true);
        }catch (\Exception $e) {
            return format_data([],$e->getMessage(),false,false);
        }
    }




    public function saveData($data)
    {
        try {
            if (empty($data['article_id'])){
                throw new MyException('article_id 不能为空');
            }
            unset($data['article_id']);
            if (empty($data['art_id'])){//add
                $msg = '添加';
                $this->Model->data($data);
                $re = $this->Model->save();
            }else{//update
                $msg = '更新';
                $re =  $this->Model->update($data);

            }
            if (empty($re)){
                throw new MyException($msg.'失败');
            }
            return format_data([],$msg.'成功',true,false);
        }  catch (MyException $e) {
            return format_data([],$e->getMessage(),true,false);
        }catch (\Exception $e) {
            return format_data([],$e->getMessage(),false,false);
        }

    }



}