<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/30
 * Time: 9:58
 * Auther sl
 */

namespace app\admin\controller\v1;

use think\Controller;
use think\Request;
use app\admin\logicModel\AutherModel;

class Auther extends Controller
{
    protected $DataModel;

    function _initialize()
    {
        $this->DataModel = new AutherModel();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function auther(Request $request)
    {
        $re = $this->DataModel->myGetList( 'getUser');

        dump($re);


        auther([$request->controller(),$request->action()]);
        $this->assign('title', '权限列表');
       // return $this->fetch();
    }

    public function addUser(Request $request)
    {
        $re = $this->DataModel->myadd($request->param(), 'User');
        return json(['param' => $request->param(), 're' => $re]);
    }


}